/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2task2;

import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.json.JSONObject;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        try {
            File inputFile = new File("input.xml");
            if (!inputFile.exists()) {
                System.out.println("The file input.xml does not exist.");
                return;
            }

            List<String> fields = new ArrayList<>();
            try (Scanner scanner = new Scanner(System.in)) {
                System.out.print("Enter the fields you want to display (comma separated): ");
                String input = scanner.nextLine();
                if (input.isEmpty()) {
                    System.out.println("No fields entered.");
                    return;
                }
                String[] fieldArray = input.split(",");
                for (String field : fieldArray) {
                    fields.add(field.trim());
                }
            } catch (Exception e) {
                System.out.println("Error reading input: " + e.getMessage());
                return;
            }

            SAXParserFactory factory = SAXParserFactory.newInstance();
            SAXParser saxParser = factory.newSAXParser();

            UserHandler userHandler = new UserHandler(fields);
            saxParser.parse(inputFile, userHandler);

            List<JSONObject> jsonObjects = userHandler.getJsonObjects();
            for (JSONObject jsonObject : jsonObjects) {
                System.out.println(jsonObject.toString(4));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
