/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2task2;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.io.File;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        try {
            File inputFile = new File("input.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(inputFile);
            doc.getDocumentElement().normalize();

            Scanner scanner = new Scanner(System.in);
            System.out.print("Enter the fields you want to display (comma separated): ");
            String[] fields = scanner.nextLine().split(",");

            NodeList nList = doc.getElementsByTagName("yourElementTag");

            for (int temp = 0; temp < nList.getLength(); temp++) {
                Node nNode = nList.item(temp);

                if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                    Element eElement = (Element) nNode;
                    for (String field : fields) {
                        field = field.trim();
                        if (eElement.getElementsByTagName(field).getLength() > 0) {
                            System.out.println(field + ": " + eElement.getElementsByTagName(field).item(0).getTextContent());
                        } else {
                            System.out.println(field + ": Not found");
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
